# Generated by Django 2.2.8 on 2019-12-10 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=4)),
                ('risk', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid Ethereum address', regex='^0x[a-fA-F0-9]{40}$')])),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
