"""
Django settings for Housteca project.

Generated by 'django-admin startproject' using Django 1.8.19.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import copy
import json
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

with open(os.path.join(BASE_DIR, 'config.json')) as file:
    ENV = json.load(file)

PRIVATE_KEY_PATH = ENV['private_key_path']
PRIVATE_KEY_PASSWORD = ENV['private_key_password']

NETWORK_ID = ENV['network_id']
HOUSTECA_ABI_FILE_PATH = ENV['housteca_abi_file_path']
LOAN_ABI_FILE_PATH = ENV['loan_abi_file_path']

# task-related settings
MAX_RUN_TIME = 60 * 60 * 3  # 3 hours
BACKGROUND_TASK_RUN_ASYNC = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV['secret_key']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV['debug']

os.environ['WEB3_PROVIDER_URI'] = ENV['web3_provider_uri']

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True

THIRD_PARTY_APPS = [
    'corsheaders',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'background_task',
]

LOCAL_APPS = [
    'users',
    'documents',
    'loans',
]

AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'housteca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'housteca.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': ENV['database']['name'],
        'USER': ENV['database']['user'],
        'PASSWORD': ENV['database']['password'],
        'HOST': ENV['database']['host'],
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

GRAPPELLI_ADMIN_TITLE = 'Housteca'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STORAGE_PATH = ENV['storage_path']

# Default authentication is "Basic base64(user:password)"
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'common.authentication.EthereumAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

SWAGGER_SETTINGS = {
    'DEFAULT_INFO': 'housteca.urls.info',
    'DEFAULT_MODEL_DEPTH': -1,
}

DEFAULT_APP_LOGGER = {
    'handlers': ['console'],
    'level': 'INFO',
    'propagate': True,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': DEFAULT_APP_LOGGER,
        **{app: copy.deepcopy(DEFAULT_APP_LOGGER) for app in LOCAL_APPS}
    },
}
